### ISSUE TITLE
Don't show internal ID when creating a new record

### ISSUE THREAD

**Issue by madebysid** [prisma/studio#156]
Internal IDs for fields don't really mean anything. Perhaps show a static text instead (We used to say `ID will be autogenerated before)

![Screenshot 2019-09-25 at 14 50 41](https://user-images.githubusercontent.com/7689783/65602256-deac2e00-dfa3-11e9-8e8d-3bcc0fda7ce4.png)

**Comment by johannesschobel** [comment]
I think it is also kind of irritating, that the `@id` field first shows a `uuid v4` id and **after** you save it, it is "converted" to whatever you have defined (`cuid()` in your case).

Maybe it is better to just use a `placeholder` (like the `null` value in the `Album` column in your example) with `autogenerated` or something? So that i can manually overwrite it if required or automatically generate a new one upon storing respective record

**Comment by johannesschobel** [comment]
this is kind-of related to #172

**Comment by madebysid** [comment]
@johannesschobel Not exactly, but I'll probably tackle them both together soon.

**Comment by madebysid** [comment]
I think this is now fixed. The ID now reads `ID will be auto-generated`.
