### ISSUE TITLE
Error in generated query: Provided Int, expected String

### ISSUE THREAD

**Issue by schickling** [prisma/studio#170]
![image](https://user-images.githubusercontent.com/1567498/65816506-d438a100-e1fc-11e9-99d2-afe7fb785ea8.png)

Repro: https://github.com/nikolasburk/datasets/tree/northwind/datasets/sqlite/northwind

**Comment by madebysid** [comment]
@schickling Using the schema you provided, I was able to reproduce this and I believe the generated query is correct. Created https://github.com/prisma/photonjs/issues/241 for it.

I don't think after should be a string here, since `order_id` is an int. Will wait to see what the result of that issue is before I jump into this!

**Comment by madebysid** [comment]
This should now be fixed with alpha.254
