### ISSUE TITLE
Display "Table"/"Tree" selection as visual button instead of dropdown

### ISSUE THREAD

**Issue by schickling** [prisma/studio#192]
Would be great to render the "Table"/"Tree" selection as visual button instead of dropdown

![image](https://user-images.githubusercontent.com/1567498/66223149-0a7d9100-e6d3-11e9-90a1-a3094b050dd0.png)

Idea similar to Mac finder selection:

![image](https://user-images.githubusercontent.com/1567498/66223175-21bc7e80-e6d3-11e9-9ea9-f77176c71c03.png)

**Comment by janpio** [comment]
In iOS these things are called "segmented controls": https://developer.apple.com/design/human-interface-guidelines/ios/controls/segmented-controls/

**Comment by madebysid** [comment]
Changed the dropdown to two buttons for the tree/table view. Didn't end up with the segmented controls since it was hard to judge which one was active (since there's only two of them). Could try icons instead as well. Closing this, but it can be changed (perhaps in a PR so you guys can experiment with it)

**Comment by schickling** [comment]
Thanks for already shipping this improvement. I'm not quite happy yet with the design of this, so keeping this issue open for now.
