### ISSUE TITLE
Unconfirmed changes count

### ISSUE THREAD

**Issue by divyenduz** [prisma/studio#241]
This might not be a clean reproduction but mid way of using studio, I noticed that the unconfirmed changes are incorrect. 

There is only 1 unconfirmed change in my UI but it shows 3. 

GIF: 

![CleanShot 2019-10-18 at 09 23 51](https://user-images.githubusercontent.com/746482/67074318-28de9480-f189-11e9-8a3f-e4c33b9b3368.gif)

1. Prisma2 version (`prisma2 -v`):
divyendusingh [cli]$ prisma2 -v
prisma2@2.0.0-alpha.253, binary version: 332b3baf392a718cffaccff674ebea649d05fcbd

2. Logs from Developer Tools Console, if any:
NA

3. Does the issue persist even after updating to the latest `prisma2` alpha (`npm i -g prisma2@alpha`)?
Yes

4. Prisma2 schema (if relevant):
I guess this is NA, the schema is from the blank project init workflow

**Comment by madebysid** [comment]
@divyenduz Ah, the count is a representation of the actions you've taken to reach that state, so I think the 3 is because you: created record, then changed `content` + `title`. Regardless, it should still be 2 rather than 3. I will look into this.

I'm also interested in investigating how the count's background color changed to gray from yellow :D

If you do run into this again, there should be an `actions` table in IndexedDB, which holds all actions. A screenshot of it expanded would help!

**Comment by madebysid** [comment]
@divyenduz Pending actions are now batched better, so that SHOULD address this in alpha.276. Let me know if you still see this.
