### ISSUE TITLE
error with studio

### ISSUE THREAD

**Issue by chrisdrackett** [prisma/studio#281]
I see the tables of my DB in the left hand column and the record counts there are correct. However clicking on anything gives me no data ("Run query to see results") and the below error:

1. Prisma2 version (`prisma2 -v`): prisma2@2.0.0-preview016.2

2. Logs from Developer Tools Console, if any:
```
Error: Error in Photon: 
Error: undefined target="exit" timestamp="2019-11-15T00:10:35.932Z" fields={"message":"255"}
    at /Users/cwd/src/calm/node_modules/prisma2/build/index.js:338787:27
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at PhotonFetcher.eval (eval at Photon.start (/Users/cwd/src/calm/node_modules/prisma2/build/index.js:93134:32), <anonymous>:73:31)
    at Generator.throw (<anonymous>)
    at rejected (/Users/cwd/src/calm/node_modules/prisma2/build/index.js:114739:69)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

3. Does the issue persist even after updating to the latest `prisma2` alpha (`npm i -g prisma2@alpha`)? 

4. Prisma2 schema (if relevant):
```

```

**Comment by madebysid** [comment]
@chrisdrackett This usually happens when Studio's trying to use an older prisma2 binary. Not sure how it got to this state, but a fresh `npm i` should re-download the correct binary and fix this.
I've also just pushed out alpha.309, so if you see this after updating to that version as well, please let me know, and I'll look into this again!

**Comment by madebysid** [comment]
@chrisdrackett This usually happens when Studio's trying to use an older/incompatible prisma2 binary. Not sure how it got to this state, but a fresh npm i should re-download the correct binary and fix this.
I've also just pushed out alpha.337, so if you see this after updating to that version as well, please let me know, and I'll look into this again!
