### ISSUE TITLE
Explicitly handle write errors in Demo deployment

### ISSUE THREAD

**Issue by claassenarjan** [prisma/studio#317]
I opened the Prisma2 Studio demo, and tried to upload attached data record. This raised an error.

**Error dump**
Cannot read property 'map' of undefined

**Stacktrace**
TypeError: Cannot read property 'map' of undefined
    at qt (https://prisma-studio.now.sh/studioBundle.js:87:22200)

![image](https://user-images.githubusercontent.com/25230009/71060789-b842fc80-2166-11ea-9074-6923e617f4dd.png)

**Comment by madebysid** [comment]
Hey @claassenarjan, the demo deployment is read-only as of right now, which is why you're running into this. I guess we should make that clear, since it doesn't say that anywhere.

I've been meaning to handle this operation more gracefully rather than failing in a cryptic way as it does right now, so I'll keep this issue open, but please note that this is expected :)

If you want to actually use Studio, I'd suggest playing around with it in a sample prisma2 template. Details [here](https://github.com/prisma/prisma2/blob/master/docs/tutorial.md)

**Comment by madebysid** [comment]
The demo deployment now explicitly handles write errors, closing!
