### ISSUE TITLE
Empty tree view is really empty

### ISSUE THREAD

**Issue by janpio** [prisma/studio#346]
```
λ npx prisma2 -v
prisma2@2.0.0-alpha.785, binary version: 3e74ccae138e0c7330c1d8f2a67fb7a234d220e8
```

![image](https://user-images.githubusercontent.com/183673/74595510-79380700-5042-11ea-8e77-6f9814939fd2.png)

**Comment by madebysid** [comment]
Fixed! There is now an illustration + some text indicating that the table is empty

<img width="1397" alt="Screenshot 2020-02-24 at 10 33 37" src="https://user-images.githubusercontent.com/7689783/75141399-2371f780-56f1-11ea-92b7-13736165e489.png">

**Comment by janpio** [comment]
Do you use "table" in Studio vs "model" in Prisma schema?

**Comment by madebysid** [comment]
There's some inconsistency here. I want to use "tables" & "rows" everywhere, since I'm thinking of Studio as a data viewing tool, but the sidebar (and other places potentially) say "Models"

IMO, a model sounds like a "definition", not a "container", aka `There are no rows in this model` just sounds weird.

I have a nomenclature discussion with @matthewmueller coming up soon, I'll bring this up and decide which direction we want to go.
