### ISSUE TITLE
"Cannot read property 'id' of undefined"

### ISSUE THREAD

**Issue by janpio** [prisma/studio#354]
https://www.notion.so/prismaio/5dff73a06d514724b00557af928fc9c1?v=faa3599cc8154ff2b0b3548e206b07e2 contains many commands for schemas to run introspection and then start Studio. Many of these fail with `Cannot read property 'id' of undefined` (Chrome, Windows)

This might be related to AUMFIDARR in the QE, but might also be caused by something in Studio itself.

**Comment by janpio** [comment]
On other systems, e.g. by @do4gr, this seems to cause this error:
`null is not an object (evaluating 't.session.script.modelId')`

**Comment by madebysid** [comment]
Tracked this down to AUMFIDAAR.

I'm fairly certain that this error will NOT go away by Clearing the cache.

Explanation (mostly for myself):
Studio currently expects every model to have an `@id` field. Now that is no longer required, and a bunch of schemas on the Notion doc have models like:
```
model AmenitiesToPlace {
  A Amenities @relation("AmenitiesTo_AmenitiesToPlace")
  B Place     @relation("PlaceTo_AmenitiesToPlace")
  @@index([B], name: "B")
  @@map("_AmenitiesToPlace")
  @@unique([A, B], name: "AmenitiesToPlace_AB_unique")
}
```

after introspection, Studio fails to generate the "autogenerated script" for these models. This is because these models do not have an `idField`. I need to make sure I handle cases where `@id` does not exist.

For completeness, here's how you can get a unique identifier for a model:

1. If there’s an `@id` on a field, that field’s `isId` is set to true
2. If we have an `@@id` clause, then the `idFields` will have all fields that are treated as Ids
3. If neither is present, we look for a @unique on a field, which will set the `isUnique` on the DMMF to true
4. If all these 3 fail, we look for an `@@unique`, which will set the `uniqueFields` to all unique fields

**Comment by janpio** [comment]
> I'm fairly certain that this error will NOT go away by Clearing the cache.

I can confirm that :)

**Comment by janpio** [comment]
> Now that is no longer required, and a bunch of schemas on the Notion doc have models like (I tested number 210):

Schema `123` might be a more real world example. It has 1 table with `@@id`, which should make it quite easy to pinpoint.

**Comment by madebysid** [comment]
alpha.898 should fix this! Please reopen if this is still reproducible!
