### ISSUE TITLE
Slow loading time for Studio

### ISSUE THREAD

**Issue by janpio** [prisma/studio#355]
The Magento schema is pretty big. If you try to run Studio for it, it takes ages before it is finished (and then fails because of https://github.com/prisma/studio/issues/354)

**Comment by madebysid** [comment]
@janpio Where does this delay happen? Does it happen in the CLI just after you run `prisma2 studio`, or is the web app slow to load?

**Comment by janpio** [comment]
Do not remember.

You can reproduce by copying and executing the command from https://www.notion.so/prismaio/5dff73a06d514724b00557af928fc9c1?v=faa3599cc8154ff2b0b3548e206b07e2 (just search for "magento")

**Comment by madebysid** [comment]
While investigating something completely different, I Was able to reproduce this. This problem is that there are way too many initial IndexedDB write transactions (the number scales linearly with the number of models and fields you have).

This will be fixed by batching these writes, or getting rid of this caching in IndexedDB completely (which I have been thinking about for a while, given that our generation has gotten pretty fast now)

**Comment by madebysid** [comment]
This is now fixed. Instead of batching things, I'm storing way less stuff now, so the problem no longer shows up.
