### ISSUE TITLE
"Cannot read property 'modelId' of null"

### ISSUE THREAD

**Issue by janpio** [prisma/studio#357]
When doing https://www.notion.so/prismaio/5dff73a06d514724b00557af928fc9c1?v=faa3599cc8154ff2b0b3548e206b07e2 we often get an error on first load of a project (Slack conversation https://prisma-company.slack.com/archives/CC8F34ALF/p1582218391001100)

If the error contains `null` in any way, e.g. `Cannot read property 'modelId' of null` or `Cannot read property 'id' of null` (Windows, Chrome), usually the link "Clear cache & reload Studio" fixes the problem and everything just works.

On other systems, e.g. by @do4gr, this seems to cause this error:
`null is not an object (evaluating 't.session.script.modelId')` or `null is not an object (evaluating 'e.id')`

**Comment by madebysid** [comment]
I'm going to investigate this one after I fix https://github.com/prisma/studio/issues/354, because I have a feeling the two might be related.
Clearing the cache *might* have worked in this scenario:
1. You opened an (unsupported) schema which had `@@id` or something
2. You open a proper supported schema.

Studio will still crash, but only because the "old" schema in IndexedDB is wrong / unsupported. So before Studio has a chance to correct itself, it crashes. After you clear the cache, there is "old" schema, so Studio works again.

So this is likely not related to the cache either.

Of course, I might be completely off too. Will know for sure after https://github.com/prisma/studio/issues/354 is fixed.

**Comment by janpio** [comment]
> So before Studio has a chance to correct itself, it crashes. After you clear the cache, there is no "old" schema, so Studio works again.

That sounds reasonable.

**Comment by madebysid** [comment]
I believe this was addresssed indeirectly in alpha.898, so closing this, but please reopen if you do see this again!
