### ISSUE TITLE
Improve UX for Error Reporting

### ISSUE THREAD

**Issue by matthewmueller** [prisma/studio#371]
1. Only show "Send Error Report" button if pressing that button will send the error to our error reporting backend. 
	- Once you press it, replace the button value with "Sending..." and disable the button (from further clicks).
	- After a successful send, replace the window with some text like "Thanks for letting us know! Here's your case ID: #123124124".
	- If an unsuccessful send, show that we were unsuccessful in sending and ask them to open a github issue with a link to a new issue.
	- Give a way to close the window and continue working in studio (reload if necessary).

2. Otherwise if it just goes to sentry, say something like "Sorry about that! We've been notified of this error and will fix it soon".

**Comment by madebysid** [comment]
This is now done.

When a fatal error occurs with something that isn't eligible to be reported to our telemetry backend, this dialog shows up:
<img width="776" alt="Screenshot 2020-03-26 at 12 00 32" src="https://user-images.githubusercontent.com/7689783/77639743-83122b80-6f59-11ea-9876-406ab43aad6e.png">

If the fatal error happened because of something that *is* eligible to be reported to our telenetry backend, this dialog shows up:
<img width="812" alt="Screenshot 2020-03-26 at 11 57 53" src="https://user-images.githubusercontent.com/7689783/77639838-a89f3500-6f59-11ea-8858-e6c1c135165a.png">

When you click on `Send Error Report`, an error report is submitted to our telemetry backend, and the dialog's content changes to:
<img width="766" alt="Screenshot 2020-03-26 at 11 59 06" src="https://user-images.githubusercontent.com/7689783/77639894-bf458c00-6f59-11ea-826f-9e63b3e3aecc.png">

Finally, if an error occured while submitting this error report to the telemetry backend, this shows up:
<img width="768" alt="Screenshot 2020-03-26 at 11 58 06" src="https://user-images.githubusercontent.com/7689783/77639934-d3898900-6f59-11ea-8fea-24d777ca94e4.png">


If they choose not to submit the error report, they can `Clear cache and reload Studio`. Do you think there needs to be a way to not clear cache and reload?
