### ISSUE TITLE
Outdated command name on disconnection error box

### ISSUE THREAD

**Issue by pantharshit00** [prisma/studio#402]
1. Prisma2 version (`prisma2 -v`):
```
@prisma/cli          : 2.0.0-beta.2
Current platform     : darwin
Query Engine         : query-engine 76857c35ba1e1764dd5473656ecbbb2f739e1822 (at /Users/harshit/.nvm/versions/node/v12.15.0/lib/node_modules/@prisma/cli/query-engine-darwin)
Migration Engine     : migration-engine-cli 76857c35ba1e1764dd5473656ecbbb2f739e1822 (at /Users/harshit/.nvm/versions/node/v12.15.0/lib/node_modules/@prisma/cli/migration-engine-darwin)
Introspection Engine : introspection-core 76857c35ba1e1764dd5473656ecbbb2f739e1822 (at /Users/harshit/.nvm/versions/node/v12.15.0/lib/node_modules/@prisma/cli/introspection-engine-darwin)
```

![image](https://user-images.githubusercontent.com/22195362/78847734-3f292700-7a2d-11ea-896b-ec0e7b0c253b.png)

The command should be `prisma` now as `prisma2` command has been deprecated.

**Comment by janpio** [comment]
Can we maybe just not mention the command at all to not put people that started via `npx prisma studio` onto a wrong command that might run a different version?

**Comment by madebysid** [comment]
Haha this again!

@janpio I like that, `prisma studio` in the error bar might not look like a command anymore either. I'll try and come up with a better message.

**Comment by madebysid** [comment]
I've changed it to `prisma studio` for now, don't want to say that "Studio server disconnected" because end users probably wouldn't know what the Studio server is. Do you guys have any suggestions for what else this might be changed to?

How does this sound: "Prisma Studio's process died. Please check your terminal and restart it using `npx @prisma/cli studio --experimental"

The cool thing about `npx` is that it would use the local installation if they have it installed, so they shouldn't end up in a weird version conflict.

**Comment by madebysid** [comment]
I've changed it to say `Prisma Studio's process died. Please check your terminal and restart it using `npx @prisma/cli studio --experimental` for now, since that felt like what made the most sense. What do you think now @janpio ?

**Comment by janpio** [comment]
I am not super sure if that is the correct command for all cases, but if it works for your now that is good enough 🤷
