### ISSUE TITLE
Numeric inputs arrow keys insistent with text input

### ISSUE THREAD

**Issue by matthewmueller** [prisma/studio#411]
In https://prisma.studio:

Numeric arrows keys are sort of nice, but not at the expense of consistency of keyboard shortcuts:

https://www.loom.com/share/f9d4f51d2dda42c1926b5796b35b05e9

Expected: numeric (and all other) inputs to behave the same with the arrow keys while editing.

**Comment by madebysid** [comment]
This is fixed now on the latest alpha (and the demo deployment)

The issue was that native number/text `input` fields in the browser show this inconsistency. So I've replace the `<input type="number" />` that renders for numeric inputs with a `<input type="text" />` and do validation myself to make sure you are not allowed to type in characters (along with a few other edge cases)
