### ISSUE TITLE
Relation "accordion" is closed when I click somewhere outside of the browser window

### ISSUE THREAD

**Issue by janpio** [prisma/studio#434]
This is from current version of https://prisma.studio/preview?project=chinook

First I open the relation thing, then click on another program on my second monitor. The relation thing closes by itself (which actually makes it hard to take screenshots of it via another tool)

![studio2](https://user-images.githubusercontent.com/183673/86344734-e8617100-bc5a-11ea-9a07-467978e3814f.gif)

**Comment by madebysid** [comment]
@janpio This is done on purpose, since that's how editing in other parts of the table also works (in string cells, clicking outside will push you out of edit mode)

Without this, closing these accordions becomes non-obvious (i.e. pressing the Esc or Enter key)

One solution I have is to keep it open for relation fields, and add a close button to the accordion. I'm not entirely sure if that's the best course of action though? Perhaps this needs a but more design input?

**Comment by janpio** [comment]
It was _very_ non obvious for me why my Studio page changed when I just switch over to Slack or other tools.

**Comment by madebysid** [comment]
This no longer occurs!
