### ISSUE TITLE
Console is full with ag-grid warnings

### ISSUE THREAD

**Issue by janpio** [prisma/studio#443]
https://prisma.studio/preview?project=chinook

![image](https://user-images.githubusercontent.com/183673/86346156-cd8ffc00-bc5c-11ea-8c70-da60a7ae36bf.png)

(I was playing around with relations in the table here)

**Comment by madebysid** [comment]
Lol yeah I have to silence these somehow, I figured they'd go away in a production build since they are warnings, but apparently not. The warnings themselves are not a problem, they show up because I'm not using ag-grid's infrastructure to do editing, I've patched it to make it work with our use case.

**Comment by madebysid** [comment]
I've started using more and more of ag-grid's APIs to do editing, so these warnings should be gone now (not from the demo deployment yet, but on the CLI). I'll update the demo deployment in a bit.

**Comment by madebysid** [comment]
Seems to be some issue in our release pipeline. Will close when it is actually out I suppose.
