### ISSUE TITLE
Consider removing the delete button

### ISSUE THREAD

**Issue by matthewmueller** [prisma/studio#459]
Currently when you first load the data browser, there's no selection. However once you click into the data browser, there's no way to unselect. This is awkward because then the delete button is always active.

I've looked at other similar UIs to see what they do and they don't actually have a delete button. They accomplish this in 2 ways:

**1. Delete from a Context menu**

<img width="963" alt="CleanShot 2020-07-06 at 12 55 10@2x" src="https://user-images.githubusercontent.com/170299/86586425-27a7fe80-bf88-11ea-9d59-beac4028da13.png">

**2. Delete from keyboard shortcut**

<kbd>Delete</kbd>

**Comment by madebysid** [comment]
@matthewmueller So I did some research for 1., and it seems there's no reliable way to add an item to the context menu on the web (unless you override it entirely), so that likely won't be possible.

For 2.: Up until now, there have been only a couple of small things you can do with *only* a shortcut (with no visual equivalent). You think just having a shortcut to delete rows would be obvious to people?

**Comment by matthewmueller** [comment]
Maybe we do a click outside in this case then. 

I'm tempted to say we should override the context menu (see Figma for a reasonable example), but given that we're trying to wrap things up, I think this can wait.

**Comment by madebysid** [comment]
I created https://github.com/prisma/studio/issues/472 to think about a custom context menu. There's potentially lots of buttons we can remove, and functionality we can add with it implemented.

I've also made it so clicking outside the table will deselect all rows (pending release)
