### ISSUE TITLE
Removing the tree view

### ISSUE THREAD

**Issue by madebysid** [prisma/studio#479]
As part of our efforts to move Studio from Experimental to GA, we've slimmed it down a little to focus on & stabilize its core use case: browsing your data & changing it.

With that, the tree view was among the few things we've decided to remove temporarily.

If anyone here would like to share use cases / things they liked about the tree view / thoughts / suggestions, please feel free!

**Comment by jeffvandyke** [comment]
I very much liked the tree view because it allows you to inspect a hierarchy more than 2 tables deep, and the ability to quickly see all parts of a hierarchal structure is something I found very handy, especially without having to write a complex join query or pull open multiple tabs. Unless if another easy and quick to use way of inspecting multi-level hierarchies comes along, I will sorely miss tree view.

**Comment by madebysid** [comment]
Hey @jeffvandyke, thanks for that. We're definitely not getting rid of it for good, it will most likely make a return in some form or another!
