### ISSUE TITLE
Trying to open a second Studio on the same port crashes in a weird way

### ISSUE THREAD

**Issue by Errorname** [prisma/studio#494]
## Bug description

Using Prisma-multi-tenant, a user sometimes needs to open two Studio for two different databases. When opening the second Studio, if the user forgot to change the default port, it will print what looks like a minified JS file (with chinese chars?) and take 100% CPU until the process is force-killed.

## How to reproduce

```
prisma init
# Add User model to schema
prisma migrate save --name=init --experimental
prisma migrate up --experimental
prisma studio --experimental

# Then, in another terminal:
prisma studio --experimental
```

## Expected behavior

It would be preferable to have a clean error saying the port is already being used.

## Environment & setup

- OS: Mac OS
- Database: Sqlite
- Node.js version: v14.5.0
- Prisma version:
```
@prisma/cli          : 2.4.1
Current platform     : darwin
Query Engine         : query-engine 195d4bdc2d16132977f4ba7a8ca312f7906cb086 (at ../../../../../usr/local/lib/node_modules/@prisma/cli/query-engine-darwin)
Migration Engine     : migration-engine-cli 195d4bdc2d16132977f4ba7a8ca312f7906cb086 (at ../../../../../usr/local/lib/node_modules/@prisma/cli/migration-engine-darwin)
Introspection Engine : introspection-core 195d4bdc2d16132977f4ba7a8ca312f7906cb086 (at ../../../../../usr/local/lib/node_modules/@prisma/cli/introspection-engine-darwin)
Format Binary        : prisma-fmt 195d4bdc2d16132977f4ba7a8ca312f7906cb086 (at ../../../../../usr/local/lib/node_modules/@prisma/cli/prisma-fmt-darwin)
```

**Comment by pantharshit00** [comment]
I can confirm this:
![image](https://user-images.githubusercontent.com/22195362/90400584-52729000-e0ba-11ea-97b5-f3e2474f6ff5.png)


Looks like it is spitting out the studio bundle. This should not happen.

**Comment by madebysid** [comment]
Hi @Errorname! While I cannot reproduce this manually, I'm guessing you saw this with prisma-mullti-tenant? We use a package called `get-port` to find an open port, and there's a warning here that may apply to your case? (https://github.com/sindresorhus/get-port#beware)
Since I have no context on prisma-multi-tenant, you're probably the best person to let me know if you think that's what's happening?

@pantharshit00 Did you also try to reproduce with `prisma-multi-tenant` or are you seeing this every time?

Regardless, the massive stack dump is an issue and I will fix it ASAP!

**Comment by pantharshit00** [comment]
I tried without prisma-multi-tenant

**Comment by Errorname** [comment]
@madebysid Sorry, I explained badly, I was just explaining the context on why anyone would open Studio twice on 2 different ports (using prisma-multi-tenant). The issue is only about the stack dump 🙂 

If studio gives a EADDRINUSE error or uses an other port, it's fine by me
