### ISSUE TITLE
Failed to validate the query: Argument does not exist on enclosing type

### ISSUE THREAD

**Issue by seanemmer** [prisma/studio#503]
1. Prisma2 version (`prisma -v`):
2.5.1-dev.5

2. Logs from Developer Tools Console, if any:
```
Error in request:  PrismaClientKnownRequestError: Failed to validate the query `Error occurred during query validation & transformation:
Query (object)
  ↳ findManyCachedCharge (field)
    ↳ take (argument)
      ↳ Argument does not exist on enclosing type.` at `.Query.findManyCachedCharge.take`
    at PrismaClientFetcher.request (/Users/sean/.cache/prisma/studio/Users-sean-Developer-pearly-app-packages-api/runtime/index.js:1:226407)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 'P2009',
  meta: {
    query_validation_error: 'Error occurred during query validation & transformation:\n' +
      'Query (object)\n' +
      '  ↳ findManyCachedCharge (field)\n' +
      '    ↳ take (argument)\n' +
      '      ↳ Argument does not exist on enclosing type.',
    query_position: '.Query.findManyCachedCharge.take'
  }
} {
  query: 'prisma.cachedCharge.findMany({\n' +
    '  take: 100,\n' +
    '  skip: 0,\n' +
    '  select: {\n' +
    '    id: true,\n' +
    '    cachedAt: true,\n' +
    '    createdAt: true,\n' +
    '    amount: true,\n' +
    '    product: true,\n' +
    '    status: true,\n' +
    '    account: true,\n' +
    '    accountId: true,\n' +
    '  }\n' +
    '})'
}
```

3. Does the issue persist even after updating to the latest `prisma` alpha? (`npm i -D @prisma/cli@dev`)

I am running the latest alpha for 2.5

**Comment by madebysid** [comment]
Hey @seanemmer, a team member today saw the same thing and he managed to fix this by deleting his `~/.cache/prisma` folder. For transparency, this is where Studio generates Prisma Client that it uses internally to make requests.

Since this is very weird to me, and I'd like to investigate, could you perhaps zip up the contents of the `~/.cache/prisma` folder and send them to me? You can send them to me on our public Slack (slack.prisma.io). My username there is `siddhant`.

The contents of that folder should really only include old downloads of Prisma engines & Prisma Client generated by Studio. It might also have your schema. If you're concerned about privacy of your schema, please let me know! (I don't think the schema is relevant though)

**Comment by seanemmer** [comment]
Great, that fixed it!

**Comment by em-ebitlabs** [comment]
Hey! 
I've got the same error.

The client was working well until I modified the schema to add a model.
The migrations ran okay, but when I make any type of query (`create`, `findMany`, etc) against the new model it always fails.

I deleted `~/.cache/prisma` but not lucky.

**Comment by madebysid** [comment]
Hey @em-ebitlabs, Studio no longer generates Prisma Client to disk, it is in-memory, so it is likely that deleting your cache folder won't make a difference anymore.

Just to make sure I understand correctly, Studio works correctly, but querying your DB from a standalone Prisma Client script fails, right? If so, maybe you forgot to re-generate Client? If not, I think it'd be best to create an issue on https://github.com/prisma/prisma if this isn't related to Studio so that the right people can take a look!

**Comment by em-ebitlabs** [comment]
Sorry @madebysid I think I don't have the same problem.

After looking a little bit more I found some people were having the same error as me https://github.com/prisma/prisma/issues/9553

I solve by downgrading prisma version from 3.5.0 to 3.0.2. Not my favourite solution but I suppose it's going to be temporally.

Thanks for your help!

**Comment by natserract** [comment]
This solution is works for me [https://github.com/redwoodjs/redwood/issues/3982](https://github.com/redwoodjs/redwood/issues/3982)
