### ISSUE TITLE
prisma studio doesn't work on Windows

### ISSUE THREAD

**Issue by oceandrama** [prisma/studio#574]
After running `prisma studio` I get the following error message in the browser

```
Message: Error in Prisma Client request: 

Error: Query engine exited with code 1

error: Found argument '--enable-experimental' which wasn't expected, or isn't valid in this context
	Did you mean --enable-playground?
USAGE:
    query-engine-windows.exe --enable-playground
```

- OS: Windows
- Database: PostgreSQL
- Node.js version: 14.5.0
- Prisma version: 2.10.1

**Comment by madebysid** [comment]
Hey @oceandrama, I've seen this issue before, but haven't been able to reliably reproduce this yet. If you did anything special after running `npm i @prisma/cli`, please let me know, I've been chasing this ghost for a while!

Could you also try running `prisma -v` and post the full output here?

Since this might be blocking you, you can also try nuking your `node_modules` directory, as well as the `%APPDATA%\Prisma` directory, which should get rid of all artifacts Studio creates.

PS: In case you're interested, the problem is that an extremely old query engine binary was somehow downloaded and is now being used (the error is what tipped me off).

**Comment by oceandrama** [comment]
@madebysid Removing `%APPDATA%\Prisma` directory works perfectly, thank you!

**Comment by madebysid** [comment]
Ah cool, they should have been updated. If this does happen again though, please let me know!
