### ISSUE TITLE
Prisma studio harm warning

### ISSUE THREAD

**Issue by Nzent** [prisma/studio#597]
Prisma studio v0.330 block from Windows defender

![image](https://user-images.githubusercontent.com/26079832/102454946-cd49b880-4064-11eb-916f-bc95b9e08c4f.png)

**Comment by madebysid** [comment]
Hi @Nzent, this is a (temporary) side effect of the certificate we use to sign our Windows app. If you press 'More Info' in this defender dialog, you should see that it is signed by Prisma.
By my understanding, this warning shows up because this is a "new" app, and will go away when enough people download and run the app and our certificate "builds" trust with Microsoft. 

If you do not see that the app is signed by Prisma though, let me know. I'm closing this for now, since this is expected. Happy to reopen if you feel otherwise!
