### ISSUE TITLE
Feature Request: Run prisma studio remotely

### ISSUE THREAD

**Issue by cyrus-za** [prisma/studio#601]
Hi,

I would love to allow our product managers, who do not have the time/know-how to clone a git repo and keep it up to date, to use prisma studio in production.

It's great that there's a native app for prisma studio, but that app still requires linking to a local schema file and if that schema file references a DB url via env, it won't work unless there's a co-located .env file or the person running the app has a global environment configured. 

What would be nice is if we could host prisma studio somewhere in a serverless environment, so that all the product manager needs to do is open the url. We can add basic auth on top of the url to restrict the outside world from accessing our DB. 

I tried running it on vercel with `npx prisma studio` command, which starts up the server but the build never finishes. Is there some way to expose a handler or something so we can do something like this on vercel?

```ts
// api/studio.ts
import { Studio } from '@prisma/client'

export default Studio.handler;
```

**Comment by Jolg42** [comment]
Hi @cyrus-za, it seems like a popular request (I did the same a few years ago with the Parse Server 👴)

I think the tracking issue for authentication would be https://github.com/prisma/studio/issues/428

And I also found this issue for an "Hosted version" https://github.com/prisma/studio/issues/492

We actually have the online demo https://prisma.studio/ hosted on Vercel, @madebysid knows more about that here.

**Comment by cyrus-za** [comment]
yep, I saw that the demo is hosted on there, which is why I was so surprised to not find any documentation on how to achieve that. 

You can close this issue. I'll follow #428 and #492

**Comment by Jolg42** [comment]
I'll keep it open and let @madebysid decide what's best 👍

**Comment by madebysid** [comment]
Let's keep this open @cyrus-za!

`npx prisma studio` starts an HTTP server, so it's no suprise that your Vercel build gets "stuck", since that command never returns :D

To deploy Studio to Vercel, there's a few things you have to do that are very much undocumented. It's not completley straight-forward to do, but since I've already done it for prisma.studio, it obviously is possible. Studio being closed-source does not help either. Let me see if I can figure out a simple way to expose this functionality over the Prisma CLI or something. Good documentation will help too.

I'll keep you in the loop!

**Comment by cyrus-za** [comment]
Thanks @madebysid and yes I know it will get stuck if it runs a http server. What would be great is if studio could export a handler function that I can add to a vercel serverless function

**Comment by madebysid** [comment]
That's a great idea! We already have a package called `@prisma/studio-preview` that has all code I use to deploy to Vercel, so my plan was to clean it up and see if that can be used directly / export the handlers like you suggest. Like I said, I'll keep you updated when I investigate!

**Comment by cyrus-za** [comment]
@madebysid any update?

**Comment by madebysid** [comment]
Oh, somehow this got closed? Bots, I tell ya..

So the guide is almost done, I'm just adding some finishing touches to it, expect something this week!

**Comment by madebysid** [comment]
@cyrus-za There's now a guide of sorts here: https://github.com/prisma/studio-vercel-guide. We decided to only "support" Vercel for now since most people seem to be using it, but I'm pretty sure the handler should work on other platforms as well (I do not use any Vercel specific helpers, just types)

We'll soon add a section to the docs too, but let me know if this help!

**Comment by cyrus-za** [comment]
Thanks @madebysid 

I missed this last message in notifications, but saw this in the 2.16.0 release just now :)

Going to tackle this ASAP and will provide feedback

**Comment by cyrus-za** [comment]
@madebysid @Jolg42 I got it working. Thanks for all the help.

Had some typical vercel monorepo issues, but got that sorted after some debugging.

Question: I've added the page protection on our enterprise vercel account, but that will just protect the pages. What is stopping people from going to yoursite.com/api/prisma/studio and making some queries to it? Ideally it should use some sort of environment variable for auth and we expose it to the frontend in a hash, but that frontend is already protected by vercel security so hackers wont have access to it.

**Comment by madebysid** [comment]
So Studio itself just isn't built with any auth stuff in mind since it is meant to be used locally. However, since you control the backend function as well, you should be able to use some sort of cookie / header based auth to validate requests before calling the `StudioHandler` from `@prisma/studio-vercel`. Can you give this a shot?

**Comment by cyrus-za** [comment]
yup that's exactly what I am busy with. The only part that is a problem is allowing us to send some error back and letting studio display it to the user, or even better if we can do res.status(401).json({redirectTo: '/login'}) then we can create our own login page and make sure that page sents the cookie on successful login. Any chance you can do a small PR to let studio frontend handle something like that?
