### ISSUE TITLE
Prisma studio showed no data

### ISSUE THREAD

**Issue by doronnac** [prisma/studio#617]
1. Prisma version (`prisma -v` or `npx prisma -v`):
@prisma/cli          : 2.14.0
@prisma/client       : 2.14.0
(also tried 2.15.0 on both)

2. Logs from Developer Tools Console or Command line, if any:
None

3. Does the issue persist even after updating to the latest `prisma` alpha? (`npm i -D @prisma/cli@dev`)
Didn't try

Table was empty in prisma studio, but querying worked
Tried to debug it for a long 15m, then decided to finally just add a row in prisma studio. After adding the row the other row suddenly appeared out of the blue.

This happened after I removed said row from within prisma studio. It was never to be seen again until I did the steps described above.

EDIT: Now trying to remove the created row from within studio doesn't work, nothing happens + no error

**Comment by madebysid** [comment]
@doronnac I had been struggling to reproduce this, but I think I've found a way to reliably do it. I just wanted to see sounds like what could have happened in your case too:

1. You opened Studio when your table had no rows
2. You added rows from somewhere outside
3. You open the table (model) in a new tab and it shows up empty. Pressing `Reload` or adding a new row makes the old ones show up.

The issue is that in step 3, Studio thinks there are no rows in the table and so does not make a `findMany` query. If you press reload or add a new row and press save, it forces Studio to send a `findMany` query and the other rows show up. These also update the row count so this never happens again.

Regardless, I'll look into this.

**Comment by doronnac** [comment]
1,2 are correct, don't recall #3 but it makes sense.
Thanks

**Comment by sbalay** [comment]
Just had the same issue for a couple of days. Refreshing the browser or even resetting the database didn't help.

Adding a new row to a table using prisma-studio made the other records show up.

**Comment by msahajwani** [comment]
I'm facing the same problem.

**Comment by madebysid** [comment]
Hey everyone, I've made a fix on `prisma@2.23.0-dev.24` that should fix this. Could you give it a shot? If it works, then this fix shuld land on stable next week. If not, please let me know!

**Comment by rajneeshshukla1608** [comment]
I having the same issue

**Comment by dipesh-m12** [comment]
Same issue ,
