### ISSUE TITLE
Allow Studio to update its own schema after a migration has run

### ISSUE THREAD

**Issue by ibadeeCodes** [prisma/studio#625]
1. Prisma version (`prisma -v` or `npx prisma -v`):
 "2.16.0"

- Inside the above model, I modified the **value** field from _Int_ to _Float_.

```
model rating {
  id      Int   @id @default(autoincrement())
  user_id Int?
  post_id Int?
  value   Float? 
}
```

- After that, I ran `prisma migrate dev --preview-feature` to sync schema.prisma with my local MySQL db.

- But when I try to enter a decimal value on the studio. It pops up an error: **value must be integer**

![studio_float_Err](https://user-images.githubusercontent.com/45182517/107274059-cc019000-6a04-11eb-924d-9bfafb5b2eaf.PNG)

The changes actually took place when I close & relaunched the studio.

But why does Prisma studio needs to be get re-launched to make this change work!
Shouldn't it make changes by pressing the refresh button at the top left as it usually does when we add or delete records?

_Ideally, Studio should re-fetch the schema immediately after migrations to reflect changes. I think it isn’t aware of changes to the schema, since it fetches the schema when launched, but subsequently, refresh only queries the database based on the schema fetched during Studio startup._

**Comment by madebysid** [comment]
Hey @ibadeeCodes, you're correct in observing that Studio only fetches your schema when it starts up.

Currently, there is no easy way to know _when_ to refetch the schema (because it changed). Watching the file system is not enough by itself because without a migration, your DB and schema are inconsistent and so Studio cannot work.

Fetching the schema on each reload / request is also incredibly wasteful, since we use an AST of the schema, which is not cheap to produce. This is why it is done once in the beginning. Perhaps when (if) we have a way to communicate with the migration engine, this will become possible.

Until then, I'll keep this open as a feature request!

**Comment by ibadeeCodes** [comment]
> Hey @ibadeeCodes, you're correct in observing that Studio only fetches your schema when it starts up.
> 
> Currently, there is no easy way to know _when_ to refetch the schema (because it changed). Watching the file system is not enough by itself because without a migration, your DB and schema are inconsistent and so Studio cannot work.
> 
> Fetching the schema on each reload / request is also incredibly wasteful, since we use an AST of the schema, which is not cheap to produce. This is why it is done once in the beginning. Perhaps when (if) we have a way to communicate with the migration engine, this will become possible.
> 
> Until then, I'll keep this open as a feature request!

**Comment by Jolg42** [comment]
Maybe Studio could watch changes to `schema.prisma` and display something like "Schema was edited since Studio was opened, click here to reload Studio"

**Comment by mankinchi** [comment]
This hasn't been implemented so why is it closed?
