### ISSUE TITLE
Embed Prisma Studio inside my Web Application

### ISSUE THREAD

**Issue by VinayaSathyanarayana** [prisma/studio#631]
I like Prisma Studio. 

- I am looking for documentation/ instructions on how I can embed Prisma Studio in my Web Application  - Front End for End Users and not in the Admin UI.
- Does Prisma Studio provide access control based on the logged in User?

**Comment by madebysid** [comment]
Hey Vinaya, this workflow is indeed important for us to enable as well. [Roadmap](https://www.notion.so/prismaio/Prisma-Roadmap-50766227b779464ab98899accb98295f?p=bf923df615b64e378ab51b4fc6ac50a6).

We're looking at this right now! I'll be sure to let you know when this is out

**Comment by VinayaSathyanarayana** [comment]
Any inputs on when is it likely to be available

**Comment by madebysid** [comment]
Hey, so I think I may have misread this. Embedding Studio inside your app can be a little tricky, because Studio is currently unfortunately closed-source. Your app's needs might be wildly different from another app's.

But I do have some suggestions:

If you have a regular server, my suggestion would be put up some sort of custom auth logic in front of the server that starts on :5555 when you run `npx prisma studio`. This could be nginx, or something you build yourself.

If you're on serverless, there's an example repo that I set up some time ago that might help you out: https://github.com/prisma/studio-vercel-guide. This is specifically for vercel, but the `@prisma/studio-vercel` package that I use in there doesn't do anything special, so I'm pretty sure it should work for other serverless platforms as well. This again, does not do any kind of authentication, so you'll have to set something up in your serverless function before you pass control to Studio's handler.

The thing I was (mistakenly) referring to was a Cloud product that will let you set up authentication and allow you to have a hosted version of Studio. This might work for you, but this isn't exactly "embedding" Studio.

Hopefully this helps. Let me know if you need more info!

**Comment by VinayaSathyanarayana** [comment]
Thanks @madebysid.   I like Prisma Studio.  I was trying to see if I can use it as a table editor in the front end in my app.

**Comment by madebysid** [comment]
Oh okay. You might be interested in ag-grid. That’s what Studio uses to build its table component. 

I don’t think your use case can be one we can support right now, so I suppose I’ll close this issue for now.
