### ISSUE TITLE
Error: Too many clients

### ISSUE THREAD

**Issue by penalosa** [prisma/studio#643]
I'm running Prisma Studio as a server to be accessible over the web, using this script (inspired from the Vercel example):
```javascript
import express from "express";
const app = express();
const port = process.env.port;
import { default as StudioHandler } from "@prisma/studio-vercel";
import path from "path";
app.get("/", (req, res) => {
  res.send("Hello World!");
});
app.use(express.json());
app.use(
  "/api",
  StudioHandler({
    schemaPath: path.resolve(__dirname, "../prisma/schema.prisma")
  })
);
app.use(express.static("node_modules/@prisma/studio/build"));
app.listen(port, () => {});
```

On the whole, it's working well, but after very little use it invariably starts failing with 

```json
{ message: "Error querying the database: db error: FATAL: sorry, too many clients already", stack: "" }
```

The rest of my codebase uses a single Prisma client that's exported from a common file (and indeed keeps working while this fails), and so I know the issue is here. It _feels_ like it might be spinning up a new client for each request, but I'm not sure — is that the case? If so, how could I fix it? Is there any way to pass in a client to be reused?

**Comment by madebysid** [comment]
Hey @penalosa!

Just so I'm clear: this isn't running on a serverless environment, right?

If it isn't, then this is to be expected. The `@prisma/studio-vercel` package that you're using is meant to run in a serverless environment, and so it never `prisma.$disconnect`s. I can add an explicit `$disconnect` call in the `@prisma/studio-vercel` package and publish a new version tomorrow for you. I'll let you know when I do that so you can give it a shot.

I'm not too sure what the rest of your setup looks like, but you can also start a regular HTTP server  just like `npx prisma studio` does. The Prisma CLI is open source, and you can use https://github.com/prisma/prisma/blob/master/src/packages/cli/src/Studio.ts#L136 as reference. You will probably be able to get away with fewer options to the constructor though.

Since we're talking about closed-source software, StudioServer's constructor doesn't have the best documentation, but here's what each option does:
```
{
      schemaPath, // Required. Absolute path to your schema.
      port, // Required. Studio-server listens on this port
      prismaClient: { // Required. Prisma Client config
        generator: { // Optional. Only needed if you plan to generate Prisma Client on the fly
          version,
          providerAliases
        },
        dir: '' // Optional. Absolute path to a pre-generated Prisma Client. You probably want this instead of `generator`.
      },
      binaryPaths: { // Optional. You can use this to override the path to the query engine that Prisma Client uses internally. You might not need this.
        queryEngine
      },
      staticAssetDir, // Optional. You can use this to override where studio-server finds frontend assets (CSS,JS etc.). You might not need this.
      versions: { // Versions of prisma & query engine used. This is only used for reporting errors. You might not need this.
        prisma2: packageJson.version,
        queryEngine: enginesVersion,
      },
}
```

I'm more than happy to help you get this working, so if you have any questions / run into issues, please feel free to let me know!

**Comment by penalosa** [comment]
Thank for getting back to me! Yeah, this isn't running in a serverless environment, just a normal express server. Adding an explicit `$disconnect` would be amazing, thank you!

In terms of using the same setup as `npx prisma studio`, that would definitely be useful — the one problem is the host. As far as I can tell, `StudioServer` doesn't expose a `host` parameter (as it does for `port`), which makes it a non-starter for docker environments (which is my use case), where it'd need to bind to `0.0.0.0` rather than just `localhost`

**Comment by penalosa** [comment]
Any updates here?

**Comment by madebysid** [comment]
Oh whoops, I think I totally forgot about this owing to some other stuff going on. Sorry about that.

I've been building some things into Studio to drive some internal efforts that will also be useful for your setup. One of these things is an in-memory version of Prisma Client. This means your `$disconnect` problem should, in theory, go away.

I've also added an option to customize Studio's backend URL (so you don't have to have a `/api` route for Studio), as well as exposing a `host` parameter to StudioServer.

If you can just give me a couple of days, I will release this and let you know (I'll make sure I don't forget this time!)

**Comment by madebysid** [comment]
@penalosa Alright, Studio 0.370.0 is out with a bunch of changes.

If you want to continue using the `@prisma/studio-vercel` package, you should be able to! It will now use an in-memory version of Prisma Client that is created on-the-fly, and also disconnects after every request.

However, if you're starting an Express server solely for this Vercel handler, you should also be able to use `@prisma/studio-server`, which exports a class that you can use to start an Express server. This has a couple of advantages in your specific setup:

1. You don't have to write your own Express server
2. You can use the newly added `hostname` param to control the hostname that the Express server binds to. I cannot expose this config on the `studio-vercel` package because there's no way for me to use the hostname there.

I *think* this should be enough to get your setup working. Let me know if you get stuck!
