### ISSUE TITLE
Prisma Studio doesn't recognize a database (Postgres) schema

### ISSUE THREAD

**Issue by minemax-ua** [prisma/studio#670]
1. Prisma Studio version: 0.359.0

I am using a database (PostgreSQL) schema different than public. The prisma migrate command does everything correctly, but the Prisma Studio is still trying to work with the public schema and throws an error: "Error: The table `public.contacts` does not exist in the current database. ..."

**Comment by madebysid** [comment]
Hey @minemax-ua, thanks for reporting! I tried creating a different schema in my Postgres DB, but Studio was able to pick it up correctly. Studio itself does not have any logic for this, this is handled by Prisma Client, so I'm wondering if Prisma Client in a stand-alone script works for you too? Just a simple one with a `findMany` should confirm this.

Also,  you probably have this already (since you said Migrate works), but doesn't hurt to confirm: do you have `?schema=newSchemaName` at the end of your connection string?

**Comment by minemax-ua** [comment]
Well, I've just tried to recreate it now again, and... everything works. I am rather confused now. Maybe I did something wrong yesterday. Sorry if that's the case.
