### ISSUE TITLE
IP Address of data browser - Needed for White list

### ISSUE THREAD

**Issue by cmcaboy** [prisma/studio#672]
**Describe the bug**
For security reasons, we have our database locked down to a finite set of IP addresses. Can you tell me what IP address I need to white list in order to get this to work?

Thank you!

**Comment by martzoukos** [comment]
Hey @cmcaboy ,

thank you for your issue.

We currently don't have any way we can expose static IPs. Does your use case depend on it in order to browse production data or do you wish to try out the tool?

Thank you!

**Comment by cmcaboy** [comment]
Yes, my use case does depend on it. We want to give our stakeholders and support team a way to easily view data. It works if we open up the IP restriction, but fails otherwise.

**Comment by martzoukos** [comment]
I see. That is an important blocker indeed, then, and I'm sorry that you're facing it.

I'll be honest about the timeline here which is that we are not going to fix that anytime soon (within the next few months). That's not because of the severity of the issue (which is high) but because of the complexity of the fix (which is also high).

The good news is that another internal team, focused on the infrastructure part of our platform, is planning to work on a hosted version of our query engine which, if we also use in our app, will solve your issue. Time frame for this is on the months scale so I'll make sure to get back to you in this issue when this happens.

Thank you for your feedback.

**Comment by martzoukos** [comment]
@cmcaboy (and everyone who is affected by this issue) we actually have great news :) ! 

We have created a solution where we can provide a static IP which you can use. In order to do that, we need to enable this feature for your project so please send your Prisma Project's URL for which you want this enabled to my email: martzoukos@prisma.io 

As a note, this is a feature that will probably be part of a paid plan in the future (end of '21 or beginning of '22) but for now it will be offered for free.

Thank you.

**Comment by martzoukos** [comment]
For anyone visiting the issue in the future, you can follow the instructions in [the Docs](https://www.prisma.io/docs/concepts/components/prisma-data-platform#static-ip-for-whitelisting) for any updates in the process.

I am now closing this issue.
