### ISSUE TITLE
Data caching

### ISSUE THREAD

**Issue by ruheni** [prisma/studio#679]
Prisma Studio seems to re-fetch data every time when connecting a relational field, making the app feel a little slow. 

It would be nice to cache data to improve performance.

Here's a screen recording explaining this: 

https://user-images.githubusercontent.com/33921841/117935812-cb7edb00-b30c-11eb-8bee-1fb4dc9cae0c.mp4

**Comment by madebysid** [comment]
Copying this over from Slack:

Hey Alex, nope Studio doesn’t cache anything currently.  I understand what you mean though. 

Caching records is not an implementation problem, but rather a logical one. We never want to show stale data. As such, it’s tricky to implement a cache (even SWR) because the experience of seeing a record appear out of nowhere, or worse, a record disappearing wouldn’t be great. 

I do acknowledge that the current implementation makes the app feel slow though, but I opted for correctness here.

There are definitely a few ideas: exact same queries in short intervals of time could definitely be cached (or SWRed) because there’s a very small chance underlying data changed in the mean time. 

I’m sure there are others too!

**Comment by V-ed** [comment]
@madebysid Adding an option for a cache duration could be your best bet here, as the burden of acknowledging stale data would be on us (you could add a warning in this new option that explains why a cache on queries might not be ideal if the data changes often).
