### ISSUE TITLE
Running prisma studio behind a nginx https reverse proxy doesn't work

### ISSUE THREAD

**Issue by KptCheeseWhiz** [prisma/studio#688]
Prisma studio always use http for its API, which trigger a mixed content error on modern browers.
```
Mixed Content: The page at 'https://xxx.xxx.com/' was loaded over HTTPS, but requested an insecure resource 'http://xxx.xxx.com/api'. This request has been blocked; the content must be served over HTTPS.
```
The offending line seems to be in `databrowser.js:3` where `window.location.protocol` should be used instead of just `http:`
```
import "./assets/index.js";
import "./assets/vendor.js";
let t = window.__vite_plugin_react_preamble_installed__ ? "http://localhost:9999/api" : `http://${window.location.host}/api`;
window.databrowser({
    transport: {
        type: "http",
        url: t
    }
});
```
Adding a breakpoint there and changing manually the value fixes the problem.

**Comment by madebysid** [comment]
Hey @KptCheeseWhiz, coincidentally, someone else reported this internally, and I've since fixed this. If you install the `dev` version of the Prisma CLI, you should be able to get this working.

You can do so by running `npm i prisma@dev`. Do note though that `dev` versions might occasionally contain breaking / unannounced changes, so I wouldn't recommend staying on them for too long. Thix fix will make it to the next stable release (2.24.0), so I would recommend upgrading to that when it comes out.
