### ISSUE TITLE
UI shaking after click on user

### ISSUE THREAD

**Issue by wangel13** [prisma/studio#717]
**Describe the bug**
UI shaking after click on user

**To Reproduce**
1. Login
2. Click on user avatar
3. See shaking

**Expected behavior**
No shaking 

**Screenshots**
[video](https://user-images.githubusercontent.com/1074859/124010423-78113b00-d9e7-11eb-9305-2050304cb92a.mp4)

**Desktop (please complete the following information):**
 - OS: Ubuntu 21.04
 - Browser - Chrome Version 91.0.4472.114 (Official Build) (64-bit)

**Comment by madebysid** [comment]
Hey @wangel13, thanks for reporting this! I think your video is private, I can't see it. It'd be great if you could upload it to Github directly!

**Comment by madebysid** [comment]
I'll upload the video here too for visibility:

https://user-images.githubusercontent.com/7689783/124114552-024fb280-da6d-11eb-8227-da3da42483b9.mp4

I see the unnecessary scrollbars too when you open up the user menu on the top right, although I don't see it appear and disappear constantly. Nevertheless, the issue is probably just the incorrect placement of the dropdown menu. Fixing it should fix this as well. I'll get on this soon!

**Comment by madebysid** [comment]
Hey, this should now be fixed!
