### ISSUE TITLE
warn(prisma-client) Already 10 Prisma Clients are actively running.

### ISSUE THREAD

**Issue by yaojiach** [prisma/studio#800]
**Describe the bug**
`warn(prisma-client) Already 10 Prisma Clients are actively running` shows shortly after starting prisma studio from command line.

**To Reproduce**
Run `prisma studio` in a project with Prisma.
Warning shows shortly after.

**Expected behavior**
`warn(prisma-client) Already 10 Prisma Clients are actively running` should not show.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]: MacOS 12.01
 - Browser [e.g. chrome, safari]: Chrome
 - Version [e.g. 22]: 95.0.4638.69

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bardsol** [comment]
I'm having the same issue after starting a new project recently. Only difference from this project is that I'm using a new database provider (supabase.com).

This only happens if I'm using the live production database URL, if I'm using my local I don't get this warning.

Is there something related to supabase?

**Comment by janpio** [comment]
It is not, and is probably also not a problem - it is just an internal warning from the Prisma Client that Prisma Studio is using under the hood.

**Comment by yaojiach** [comment]
@janpio thanks. hope it'll be resolved in future releases. really awesome tool to quickly access and manipulate data.

**Comment by madebysid** [comment]
This should be fixed on the latest Prisma CLI `dev` version (`3.8.0-dev.46` as of writing). Could you update your CLI and let me know if you're still seeing this?
This will make it the stable CLI with the next release (next Tuesday). You can keep using the `dev` version if you'd like, but I'd recommend upgrading to `3.8.0` when it goes out, since `dev` versions are mostly for internal use and may contain unannounced breaking changes.

Let me know if you're still seeing this!
