### ISSUE TITLE
Installation on Mac Desktop does not work.

### ISSUE THREAD

**Issue by alissanguyen** [prisma/studio#824]
### Bug description

![Screen Shot 2022-01-03 at 7 37 09 PM](https://user-images.githubusercontent.com/69443738/148006436-321d77d0-f8fa-4986-a4d9-1861228819e0.png)

I'm getting the following error when installing Prisma Studio for my Mac. I have macOS Monterey 12.0.1.

Below are my system specs.
**Hardware Overview:**
  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro18,3
  Chip:	Apple M1 Pro
  Total Number of Cores:	8 (6 performance and 2 efficiency)
  Memory:	16 GB
  System Firmware Version:	7429.41.5
  OS Loader Version:	7429.41.5

### Expected behavior

The Mac client should install successfully.

### Prisma information

N/A

### Environment & setup

- OS: MacOS Monterey
- Database: N/A

### Prisma Version

```
N/A
```

**Comment by madebysid** [comment]
Hey @alissanguyen, thanks fior bringing this up! Our apps are usually notarized, but I've found an issue with our internal setup that was silently failing. For now, you can do what @pantharshit00 suggested and right-click > Open to open the app the first time.

I'm looking into our build setup failure and will make sure un-notarized apps fail the pipeline instead of silently failing.

**Comment by madebysid** [comment]
I just released a new version of the Electron app with this issue fixed. Since you already have the app now, you can just upgrade, but this is resolved for people who download the app in the future!
