### ISSUE TITLE
Fatal ERORR

### ISSUE THREAD

**Issue by Programming-School-Pro-Coding** [prisma/studio#869]
1. Prisma version (`prisma -v` or `npx prisma -v`):

2. Logs from Developer Tools Console or Command line, if any:
```
error - Error:
Invalid `prisma.guestbook.findMany()` invocation:


  Error querying the database: Server error: `ERROR HY000 (1105): unknown error: Code: UNAVAILABLE
server does not allow insecure connections, client must use SSL/TLS
'
error - Error:
Invalid `prisma.guestbook.findMany()` invocation:


  Error querying the database: Server error: `ERROR HY000 (1105): unknown error: Code: UNAVAILABLE
server does not allow insecure connections, client must use SSL/TLS
'
error - Error:
Invalid `prisma.guestbook.findMany()` invocation:


  Error querying the database: Server error: `ERROR HY000 (1105): unknown error: Code: UNAVAILABLE
server does not allow insecure connections, client must use SSL/TLS
'
```

3. Does the issue persist even after updating to the latest `prisma` CLI dev version? (`npm i -D prisma@dev`)

4. Prisma schema (if relevant):
```
Message: Error in Prisma Client request: 


Invalid `prisma.guestbook.findMany()` invocation:


  The table `(not available)` does not exist in the current database.
  
Query:
[object Object]
```

Please Help me

**Comment by janpio** [comment]
What database provider are you suing?
Are you using the Prisma CLI or cloud.prisma.io?

**Comment by heymartinadams** [comment]
I’ve run into the same error: `The table `(not available)` does not exist in the current database`, even after deleting the IndexedDB database and clearing all site data, including 3rd-party cookies, then signing in again from scratch.

It seems that either Prisma Studio isn’t reflecting the changes to the database schema, or the database schema hasn’t updated. Using PlanetScale.

**Comment by heymartinadams** [comment]
If we compare the Prisma Studio console log, which shows an outdated schema, with the db schema, we can see the discrepancy.

## Prisma Cloud
![CleanShot 2022-12-05 at 11 14 50@2x](https://user-images.githubusercontent.com/11673745/205723371-e13a297f-b4b2-4143-824a-f48e7013999e.png)

Here’s the current schema in PlanetScale (I made sure to refresh). The relation `Circles` (note the plural, since this was a one-to-many relation) has been removed, and a new optional one-to-one relation `User` has been added.

## PlanetScale
<img width="615" alt="CleanShot 2022-12-05 at 11 16 06@2x" src="https://user-images.githubusercontent.com/11673745/205723613-005a369d-1606-4d66-9704-922cdc1a8338.png">

**Comment by heymartinadams** [comment]
Nevermind! **I moved the GitHub repository to a new GitHub organization!** That’s why Prisma Studio didn’t update. Needed to set up a new Prisma Cloud repository as a result.

Leaving my above documented (mis-)adventures for others to see, in case it’s helpful.
