### ISSUE TITLE
Bug for selected record

### ISSUE THREAD

**Issue by schickling** [prisma/studio#94]
https://www.loom.com/share/2f48726dcdf14c529bb27e77192f8e2c

**Comment by madebysid** [comment]
I think I might know what's happening here. Do you have three records in total, and you're fetching the first two at a time?

You've selected the one with email `test`. The store that saves the "active record" knows this. When you sort in ascending, that record isn't returned at all, so nothing is selected. When you sort in descending, it does get returned, and is selected. (Does this make sense?)

I'm going to change behaviour so re-running a script deselects all records, that should get rid of this, because this does look weird.

**Comment by schickling** [comment]
> I'm going to change behaviour so re-running a script deselects all records, that should get rid of this, because it does look weird.

Does this mean you don't preserve the selected record across refetches?

**Comment by madebysid** [comment]
Well yeah.

**Comment by madebysid** [comment]
It is bound to the ID field (selected record is `User::ck03lt...7rg`), but the record that is supposed to be selected isn't returned at all when you sort by `asc`. 

A little weird, but: I could also see if the currently selected record still exists(is returned) after a request, and keep it, or clear selection if it doesn't?

**Comment by schickling** [comment]
> A little weird, but: I could also see if the currently selected record still exists(is returned) after a request, and keep it, or clear selection if it doesn't?

Sounds great!

**Comment by madebysid** [comment]
Out with alpha.176
