### ISSUE TITLE
Clicking on JSON preview should toggle record

### ISSUE THREAD

**Issue by schickling** [prisma/studio#98]
https://www.loom.com/share/e977a651a41b49889a8d341cece543d7

**Comment by madebysid** [comment]
Right, so about this, it is done so that clicking the arrow or the "label" (the thing that says Post) opens the record. If someone wants to copy the stringified object for some reason, it might be annoying if the record just opens up (I have this annoyance with Chrome DevTools :P )

But can change that if you confirm that it is not that common!

**Comment by schickling** [comment]
I think it's not that common since it's just partial anyway. In case this is a common use case we should add a "copy to clipboard as JSON" flow for a given row (cc @kuldar).
